fail_fast: true

repos:
  - repo: local
    hooks:
      - id: pylint
        name: Local PyLint
        language: system
        require_serial: true
        types:
          - python
        exclude: "^[^/]*env/|dev-[^/]*/"
        entry: pylint -j 0
      - id: mypy
        name: Local MyPy
        language: system
        types:
          - python
#        files: \.py$
        exclude: "^[^/]*env/|dev-[^/]*/"
        require_serial: true
#        entry: ./basic-installer.bash mypy --strict
        entry: mypy --strict --show-error-codes --no-warn-unused-ignores

#  - repo: https://github.com/PyCQA/pylint
#    rev: v2.13.9
#    hooks:
#      - id: pylint
#        args: [ -j, "0", --disable=all, --enable=unused-import]

  - repo: https://github.com/jmfernandez/pre-commit_mirrors-tan
    rev: v23.3.0
    hooks:
      - id: tan
        exclude: "^[^/]*env/|dev-[^/]*/"
        args: [--diff, --check, --use-tabs]

#  - repo: local
#    hooks:
#      - id: citation.cff
#        name: CITATION.CFF checker
#        always_run: true
#        pass_filenames: false
#        language: system
#        files: "^CITATION.cff$"
#        entry: python dev-scripts/cff-ver-validate.py CITATION.cff
