fail_fast: true

repos:
  - repo: https://github.com/PyCQA/pylint
    rev: v2.15.2
    hooks:
      - id: pylint
        args: [ -j, "0", --disable=all, --enable=unused-import]

  - repo: local
    hooks:
      - id: mypy
        name: Local MyPy
        language: system
        types: [file, python]
#        files: \.py$
        exclude: "^[^/]*env/|dev-[^/]*/"
        require_serial: true
        entry: mypy --strict

  - repo: https://github.com/jmfernandez/pre-commit_mirrors-tan
    rev: v22.8.0
    hooks:
      - id: tan
        exclude: "^[^/]*env/|dev-[^/]*/"
        args: [--diff, --check, --use-tabs]

#  - repo: local
#    hooks:
#      - id: citation.cff
#        name: CITATION.CFF checker
#        always_run: true
#        pass_filenames: false
#        language: system
#        files: "^CITATION.cff$"
#        entry: python dev-scripts/cff-ver-validate.py CITATION.cff
