name: PyPI Deployment
# if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags'A
on:
  push:
    tags:
     - v*
jobs:
  testpypi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install development dependencies
        uses: py-actions/py-dependency-install@v2.1.0
        with:
          path: "dev-requirements.txt"
      - name: Build packages to be uploaded
        run: python -m build
      - name: pypi-publish
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

