name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
    name: Pre-commit python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          architecture: x64
      - run: pip install --upgrade pip wheel
      - run: |
          pip install -r requirements.txt
          pip freeze > constraints-${{ matrix.python-version }}.txt
      - name: Check transitive dependencies licences
        id: license_check_report
        uses: pilosus/action-pip-license-checker@v0.6.2
        with:
          requirements: constraints-${{ matrix.python-version }}.txt
          fail: 'StrongCopyleft'
          exclude: 'pylint.*'
      - name: Print licences report
        if: ${{ always() }}
        run: echo "${{ steps.license_check_report.outputs.report }}"
      - run: pip install -r dev-requirements.txt -r mypy-requirements.txt
      - name: MyPy cache
        uses: actions/cache@v3
        with:
          path: .mypy_cache/${{ matrix.python-version }}
          key: mypy-${{ matrix.python-version }}
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all -c .pre-commit-config-gh.yaml
      - uses: actions/upload-artifact@v3
        with:
          retention-days: 2
          path: constraints-${{ matrix.python-version }}.txt
          
  pre-commit_3-6:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.6" ]
    name: Pre-commit python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
          architecture: x64
      - run: pip install wheel
#               pip install -r requirements.txt -r requirements-additional-${{ matrix.python-version }}.txt
      - run: |
          pip install -r requirements.txt
          pip freeze > constraints-${{ matrix.python-version }}.txt
      - name: Check transitive dependencies licences
        id: license_check_report
        uses: pilosus/action-pip-license-checker@v0.6.2
        with:
          requirements: constraints-${{ matrix.python-version }}.txt
          fail: 'StrongCopyleft'
          exclude: 'pylint.*'
      - name: Print licences report
        if: ${{ always() }}
        run: echo "${{ steps.license_check_report.outputs.report }}"
      - run: pip install -r dev-requirements.txt -r mypy-requirements.txt
      - name: MyPy cache
        uses: actions/cache@v3
        with:
          path: .mypy_cache/${{ matrix.python-version }}
          key: mypy-${{ matrix.python-version }}
      - uses: pre-commit/action@v3.0.0
        with:
          extra_args: --all -c .pre-commit-config-gh-${{ matrix.python-version }}.yaml
      - uses: actions/upload-artifact@v3
        with:
          retention-days: 2
          path: constraints-${{ matrix.python-version }}.txt
  
  push_constraints:
    runs-on: ubuntu-latest
    name: Store newly generated constraints
    needs:
      - pre-commit
      - pre-commit_3-6
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          path: constraints-dir
      - name: Move artifacts to their right place
        run: mv constraints-dir/artifact/* .
      - uses: EndBug/add-and-commit@v9
        with:
          add: constraints-*.txt
          message: Automatically commit changed constraints
          default_author: github_actions
    